### ISSUE TITLE
Document how to parse indentation based grammars

### ISSUE THREAD

**Issue by MTRNord** [alecthomas/participle#20]
Hi I want to check if the prevoius char is a `:`. The exact example code I have is this:

```
Prefix: !
```

I want basicly to be able to check based on if the previous char is a `:` the `!` should get a string and later reuse the look back logic to check if I am inside an array which is defined like in yaml meaning to make sure the last 2 lines of the following example don't get into the array:

```
Commands:
    - Trigger: afk
      Response: "{{user}} just went afk"
    - Trigger: [join_event]
      Response: "Welcome to the Room {{last_joined_user}}"
Homeserver: matrix.org
HomeRoom: {{name}}
```

(Commands defines a Array with 2 objects in it which both have two key value pairs in them. HomeServer and HomeRoom are outside of that array)

**Comment by alecthomas** [comment]
You cannot perform look-behind with Participle.

If you're trying to parse YAML, you will almost certainly need a custom lexer that includes indentation as a first-class token. 

If you could describe and give examples of both situations where the `!` is used that require the look-behind, I might be able to help further.

**Comment by MTRNord** [comment]
The `!` is just any char possible. I wanted to stringify anything after the `:` before a new line. But thats something I have no problem with if that is impossible.

The yaml like array is something I woud like to be able to have. In that case of arrays a look behind would be nice or as you mentioned a way to check the identation to see if I am inside an array.

**Comment by alecthomas** [comment]
I more meant that if you show me an example of what you're trying to achieve I may be able to provide you with a grammar that will parse it.

**Comment by MTRNord** [comment]
Oh ok. I can do that later this day.

**Comment by MTRNord** [comment]
So my current code is at https://github.com/Nordgedanken/Matrix-DSL I tried to have a custom lexer based on participle but as you mentioned look-behind failed (nil pointers^^). You can find the gramar I am using at https://github.com/Nordgedanken/Matrix-DSL/blob/master/cmd/lexer/ast.go

The full example I currently have is:

```
[[BOT]]
Name: Test Bot
Description: Some Demo Bot
Prefix: !
Autojoin: true
Commands:
    - Trigger: afk
      Response: {{user}} just went afk
    - Trigger: [join_event]
      Response: Welcome to the Room {{last_joined_user}}
Homeserver: matrix.org
HomeRoom: {{name}}
```

So lets break up how I wanted to have this parsed:

1. `[[BOT]]` is a header for the type of config. This already works
2. From "Name" to "Autojoin" there are 4 key value pairs which I want to parse into a string. This currently fails as the default lexer requires me to have `"` around strings.
3. "Commands" starts a Array. This is exact the same as yaml defines it. But with the same type of strings as mentioned in 2. The first line of a object has a `-` as a prefix. The following key value pairs inside the object are on the same "level" (have the same amount of spaces in front)
4. `[join_event]` are special keys that are predefined.
5. Strings with `{{}}` around them are also special keys but reflect either predefined variables or variables from the Config. (these can be parsed after the work of participle just fine as they get replaced anyway)
6. "Homeserver" and "HomeRoom" are like the pairs in 1 but are after the array means I need some kind of tracking if we left the array.
